name: build hello

on: [push]

jobs:
  build-x86:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install --yes build-essential make

      - name: Build hello binary
        shell: bash
        run: |
          cd src
          make

      - name: Test hello binary
        shell: bash
        run: |
          cd src
          ls -al
          file hello
          printf "Run hello:\n"
          ./hello

  build-x86-ustreamer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "pikvm/ustreamer"
          ref: "master"
          path: "ustreamer"

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install --yes build-essential make

      - name: Install ustreamer dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install --yes libevent-dev libjpeg-dev libbsd-dev

      - name: Build ustreamer binary
        shell: bash
        run: |
          cd ustreamer
          export CFLAGS="-O3 -static"
          export LDFLAGS="-static"
          make -j$(nproc)

      - name: Test hello binary
        shell: bash
        run: |
          cd ustreamer
          ls -alh
          file src/ustreamer.bin
          printf "Test ustreamer:\n"
          printf "ustreamer version: %s\n" "$(./ustreamer --version)"
          echo "::group::Print ustreamer help"
          ./ustreamer --help
          echo "::endgroup::"
