name: build hello

on: [push]

jobs:
  build-x86:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install --yes build-essential make

      - name: Build hello binary
        shell: bash
        run: |
          cd src
          make

      - name: Test hello binary
        shell: bash
        run: |
          cd src
          ls -al
          file hello
          echo "Run hello:\n"
          ./hello
